export default function Vision() {
    return (
        <section className="py-16 px-4 md:px-8 lg:px-16 bg-white text-gray-800">

            <div className="max-w-7xl mx-auto text-center mb-16">
                <h3 className="text-xl md:text-2xl lg:text-3xl font-medium text-[#577038] mb-4">
                    Our vision is to create a greener and cleaner world using heat pump technology to deliver
                    reliable, efficient, and affordable hot water that serves to minimise carbon footprint and
                    maximise social impact. We aspire to be the global leader in Heat Pump technology.
                </h3>
            </div>
            <div className="text-center mb-8">
                <h4 className="text-2xl font-medium text-[#333] mb-2">A little more about our journey</h4>
            </div>
            <div className="max-w-7xl mx-auto grid md:grid-cols-2 gap-8 md:gap-12 items-start">

                <div className="text-gray-700 space-y-4">
                    <p>
                        <strong>Ecogenica</strong> is an Australian owned designer, wholesaler, and manufacturer
                        of Heat Pumps.
                    </p>
                    <p>
                        The Ecogenica Brand specialises in Heat Pump hot water upgrades and installations and is
                        a major participant in numerous state and federal government energy savings schemes.
                    </p>
                </div>

                <div className="border-l-4 border-green-700 pl-6 text-gray-700 space-y-4">

                    <p>
                        The Ecogenica brand was launched with the sole focus on Heat Pump technology. We have a
                        wealth of talent and experience in technology innovation, using sustainable and renewable
                        energy to deliver hot water to homes and businesses across Australia.
                    </p>
                    <p>
                        The Ecogenica Brand has been installed in over 200,000 homes & businesses since the
                        launch of our first Heat Pumps in 2018. Ecogenica estimates that close to a million
                        Australians experience hot water generated by our heat pumps every day!
                    </p>
                    <p>
                        Our new U.K. models are A+++ rated and our EG-290FR (290lt residential unit) heat pump
                        has the highest COP in the Australian market. It produces 5.7 KW of energy from 1KW of
                        electricity consumed.
                    </p>
                    <p>
                        Ecogenica also offers installation services for its customers. Ecogenica is committed to
                        greener and healthier technology and aims to reduce costs and expenses for its customers,
                        saving customers money every day off their power bill.
                    </p>
                </div>
            </div>
        </section>
    );
}
